const personalityDisorders=[
    DEPRESSION = {
        id:0,
        symptom1: "A narcissist believes that they are more important than and superior to everyone else.",
        symptom2: "A narcissist's perception of themselves is over-inflated and not fully grounded in reality.",
        symptom3: "A narcissist would have a tendency to not care about interpersonal connections with people based on kindess and love.", 
        symptom4: "They have very little or no empathy towards others.",
        symptom5: "A narcissist are interested in gaining wealth and influence even at the expense of others. They will lie or manipulate to obtain their goals",
        symptom6: "A narcissist may have a very small emotional range.",
        symptom7: "A narcissist could find it hard or almost unthinkable to admit they were wrong.",
        symptom8: "A narcissist could feel disinterested or aimless.",
    },
    NARCISSISM = {
        id:1,
        symptom1: "A narcissist believes that they are more important than and superior to everyone else.",
        symptom2: "A narcissist's perception of themselves is over-inflated and not fully grounded in reality.",
        symptom3: "A narcissist would have a tendency to not care about interpersonal connections with people based on kindess and love.", 
        symptom4: "They have very little or no empathy towards others.",
        symptom5: "A narcissist are interested in gaining wealth and influence even at the expense of others. They will lie or manipulate to obtain their goals",
        symptom6: "A narcissist may have a very small emotional range.",
        symptom7: "A narcissist could find it hard or almost unthinkable to admit they were wrong.",
        symptom8: "A narcissist could feel disinterested or aimless.",
    },
    
    PSYCHOPATHY = {
        id:2,
        symptom1: "A narcissist believes that they are more important than and superior to everyone else.",
        symptom2: "A narcissist's perception of themselves is over-inflated and not fully grounded in reality.",
        symptom3: "A narcissist would have a tendency to not care about interpersonal connections with people based on kindess and love.", 
        symptom4: "They have very little or no empathy towards others.",
        symptom5: "A narcissist are interested in gaining wealth and influence even at the expense of others. They will lie or manipulate to obtain their goals",
        symptom6: "A narcissist may have a very small emotional range.",
        symptom7: "A narcissist could find it hard or almost unthinkable to admit they were wrong.",
        symptom8: "A narcissist could feel disinterested or aimless.",
    },
    PTSD = {
        id:3,
        symptom1: "A narcissist believes that they are more important than and superior to everyone else.",
        symptom2: "A narcissist's perception of themselves is over-inflated and not fully grounded in reality.",
        symptom3: "A narcissist would have a tendency to not care about interpersonal connections with people based on kindess and love.", 
        symptom4: "They have very little or no empathy towards others.",
        symptom5: "A narcissist are interested in gaining wealth and influence even at the expense of others. They will lie or manipulate to obtain their goals",
        symptom6: "A narcissist may have a very small emotional range.",
        symptom7: "A narcissist could find it hard or almost unthinkable to admit they were wrong.",
        symptom8: "A narcissist could feel disinterested or aimless.",
    },
    
    SCHIZOID = {
        id:4,
        symptom1: "A narcissist believes that they are more important than and superior to everyone else.",
        symptom2: "A narcissist's perception of themselves is over-inflated and not fully grounded in reality.",
        symptom3: "A narcissist would have a tendency to not care about interpersonal connections with people based on kindess and love.", 
        symptom4: "They have very little or no empathy towards others.",
        symptom5: "A narcissist are interested in gaining wealth and influence even at the expense of others. They will lie or manipulate to obtain their goals",
        symptom6: "A narcissist may have a very small emotional range.",
        symptom7: "A narcissist could find it hard or almost unthinkable to admit they were wrong.",
        symptom8: "A narcissist could feel disinterested or aimless.",
    },
    SOCIOPATHY = {
        id:5,
        symptom1: "A narcissist believes that they are more important than and superior to everyone else.",
        symptom2: "A narcissist's perception of themselves is over-inflated and not fully grounded in reality.",
        symptom3: "A narcissist would have a tendency to not care about interpersonal connections with people based on kindess and love.", 
        symptom4: "They have very little or no empathy towards others.",
        symptom5: "A narcissist are interested in gaining wealth and influence even at the expense of others. They will lie or manipulate to obtain their goals",
        symptom6: "A narcissist may have a very small emotional range.",
        symptom7: "A narcissist could find it hard or almost unthinkable to admit they were wrong.",
        symptom8: "A narcissist could feel disinterested or aimless.",
    }, 
    
]